@Links.Api_HostAddress = http://localhost:1337

POST http://localhost:1337/links
Content-Type: application/json
Authorization: bearer SOME_VALUE_YOU_GET_FROM_ANOTHER_SERVICE

{
    "href": "https://developer.mozilla.org/en-US/",
    "description": "All things Web - javaScript, html, css - all of it",
    "title": "Mozilla Developer  Network"
}


###

GET http://localhost:1337/links
Accept: application/json 

